VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
    v.name = "a10-threatstop"
  end

  config.vm.define "threatstop1" do |threatstop1|
    threatstop1.vm.box = "ubuntu/trusty64"
    threatstop1.vm.network "forwarded_port", guest: 80, host: 8088
    threatstop1.vm.network "forwarded_port", guest: 443, host: 8443
    threatstop1.vm.network "public_network", bridge: "<interface>", ip: "<optional>"
    threatstop1.vm.network "public_network", bridge: "<interface>", ip: "<optional>"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo add-apt-repository -y ppa:webupd8team/atom
    sudo apt-get update
    sudo apt-get install -y lubuntu-desktop
    sudo apt-get install -y git
    sudo apt-get install -y python3-dev python3-pip
    sudo apt-get install -y atom
    sudo apt-get install -y bpython3
    sudo apt-get install -y idle3
    sudo apt-get install -y vim-athena
    sudo apt-get install -y vim-python-jedi
    sudo pip3 install --upgrade pip3
    sudo pip3 install --upgrade virtualenv
    sudo pip3 install --upgrade virtualenvwrapper
    sudo pip3 install --upgrade jupyter
    sudo pip3 install --upgrade ipython
    sudo apt-get -y autoremove
    echo "Copying Threastop.conf to /etc/threatstop/"
    mkdir /etc/threatstop/
    cp /vagrant/threatstop.conf /etc/threatstop/
  SHELL

end
